[package]
name = "sprite-render"
version = "0.1.0"
authors = ["Rodrigodd"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

opengl = ["glutin", "gl"]
webgl = ["winit/web-sys"]

[dependencies]

cfg-if = "0.1"
memoffset = "0.5"
winit = "0.22"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = { version = "0.24", optional = true }
gl = { version = "0.14", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.39"
wasm-bindgen = "0.2.62"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
  'Document',
  'Element',
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlRenderingContext',
  'WebGlUniformLocation',
  'WebGlProgram',
  'WebGlShader',
  'WebGlTexture',
  'Window',
]

[dev-dependencies]

winit = "0.22"
rand = "0.7"
image = "0.23"